name: Automatizacion de Noticias

on:
  schedule:
    - cron: '0 */4 * * *' # El robot se ejecutará automáticamente cada 4 horas
  workflow_dispatch: # Mantiene tu botón manual de emergencia

permissions:
  contents: write

jobs:
  procesar-noticias:
    runs-on: ubuntu-latest
    steps:
      - name: Traer el código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4 google-genai

      - name: Ejecutar la IA
        env:
          LLAVESECRETABRAI: ${{ secrets.LLAVESECRETABRAI }}
        run: python recolector.py

      - name: Guardar la nueva web en internet
        run: |
          git config --global user.name 'Bot de Finanzas'
          git config --global user.email 'bot@mercadolocal.com'
          git add .
          git commit -m "Web actualizada automáticamente" || echo "Sin cambios"
          git push
